"""Generate PDF report from structured data using Jinja2 + WeasyPrint."""

import io
from datetime import datetime

from jinja2 import Template

REPORT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1a1a1a; max-width: 800px; margin: 0 auto; padding: 40px; }
  h1 { color: #0074c5; border-bottom: 3px solid #0074c5; padding-bottom: 10px; }
  h2 { color: #333; margin-top: 30px; }
  .score-box { background: #f0f7ff; border: 2px solid #0074c5; border-radius: 12px; padding: 20px; text-align: center; margin: 20px 0; }
  .score-value { font-size: 48px; font-weight: bold; color: #0074c5; }
  .grade { font-size: 24px; color: #666; }
  .sub-scores { display: flex; gap: 15px; margin: 15px 0; flex-wrap: wrap; }
  .sub-score { flex: 1; min-width: 120px; background: #f9f9f9; border-radius: 8px; padding: 12px; text-align: center; }
  .sub-score .value { font-size: 24px; font-weight: bold; }
  .sub-score .label { font-size: 11px; color: #666; text-transform: uppercase; }
  .metric-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #eee; }
  .rec { border-left: 4px solid; padding: 10px 15px; margin: 10px 0; background: #fafafa; border-radius: 0 8px 8px 0; }
  .rec.high { border-color: #dc2626; }
  .rec.medium { border-color: #f59e0b; }
  .rec.info { border-color: #0074c5; }
  .rec-title { font-weight: 600; margin-bottom: 4px; }
  .rec-desc { color: #555; font-size: 14px; }
  table { width: 100%; border-collapse: collapse; margin: 10px 0; }
  th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid #eee; }
  th { background: #f5f5f5; font-weight: 600; }
  .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #999; font-size: 12px; text-align: center; }
</style>
</head>
<body>
  <h1>Ergon Manipulation Quality Report</h1>
  <p>Job: <code>{{ job_id[:8] }}...</code> | Environment: {{ environment }} | Generated: {{ generated_at }}</p>

  <div class="score-box">
    <div class="score-value">{{ overall_score }}/100</div>
    <div class="grade">Grade: {{ grade }}</div>
  </div>

  <div class="sub-scores">
    {% for name, score in sub_scores.items() %}
    <div class="sub-score">
      <div class="value">{{ score }}</div>
      <div class="label">{{ name.replace('_', ' ') }}</div>
    </div>
    {% endfor %}
  </div>

  {% if object_info.properties %}
  <h2>Object Properties</h2>
  <table>
    {% for key, value in object_info.properties.items() %}
    <tr><td>{{ key.replace('_', ' ').title() }}</td><td>{{ value }}</td></tr>
    {% endfor %}
  </table>
  {% endif %}

  {% if object_info.geometry %}
  <h2>Geometry Summary</h2>
  <table>
    {% for key, value in object_info.geometry.items() %}
    <tr><td>{{ key.replace('_', ' ').title() }}</td><td>{{ value }}</td></tr>
    {% endfor %}
  </table>
  {% endif %}

  <h2>Detailed Metrics</h2>
  {% for name, metric in metrics.items() %}
  <h3>{{ name.replace('_', ' ').title() }}</h3>
  <table>
    {% for key, value in metric.items() %}
    {% if key not in ['by_task', 'details', 'categories'] %}
    <tr><td>{{ key.replace('_', ' ').title() }}</td><td>{{ value }}</td></tr>
    {% endif %}
    {% endfor %}
  </table>
  {% endfor %}

  <h2>Recommendations</h2>
  {% for rec in recommendations %}
  <div class="rec {{ rec.severity }}">
    <div class="rec-title">{{ rec.title }}</div>
    <div class="rec-desc">{{ rec.description }}</div>
  </div>
  {% endfor %}

  <div class="footer">
    Generated by Ergon — CAD to Manipulation Quality Platform
  </div>
</body>
</html>
"""


def generate_pdf(report_data: dict) -> bytes:
    """Generate PDF from report data."""
    template = Template(REPORT_TEMPLATE)
    html = template.render(**report_data)

    try:
        from weasyprint import HTML
        pdf_bytes = HTML(string=html).write_pdf()
        return pdf_bytes
    except Exception:
        # Fallback: return HTML as bytes if WeasyPrint unavailable
        return html.encode()
